### ISSUE TITLE
회원 별 옷차림 저장 api

### ISSUE THREAD

**Issue by phk1128** [FashionForecast/FashionForecast-server#115]
### 📄 Describe

회원 별 옷차림 저장 api 구현

### ✅ Tasks

- [x] 엔티티 구현
- [x] 서비스 레이어 구현
- [x] 컨트롤러 구현
- [x] 테스트 코드 작성
- [x] api 명세서 작성

### 🙋🏻 More

✅ todo 
- 상의, 하의 옷유형 조회 api 구현
- 회원 별 옷차림 조회 api 구현
- 회원 별 옷차림 수정 및 삭제 api 구현
