### ISSUE TITLE
회원 설정

### ISSUE THREAD

**Issue by cherryiJuice** [FashionForecast/FashionForecast-server#129]
### 📄 Describe

- 기본 위치 설정(저장,조회,삭제)
- 기본 외출시간 설정(저장,조회,삭제)
- 기본 옷차림 두께 설정(저장,조회,삭제)

### ✅ Tasks

- [ ] 기본 위치 설정
- [ ] 기본 외출시간 설정
- [ ] 기본 옷차림 두께 설정
