### ISSUE TITLE
cicd 및 도커라이징 작업

### ISSUE THREAD

**Issue by phk1128** [FashionForecast/FashionForecast-server#19]
### 📄 Describe

aws 개발 서버로 cicd를 적용하고, 배포시에 Docker를 이용할려고 합니다.

### ✅ Tasks

- [ ] aws 개발서버 환경 세팅
- [ ] 개발서버 전용 cicd 스크립트 작성
- [ ] Dockerfile 및 docker-compose 스크립트 작성
- [ ] cicd 테스트
