### ISSUE TITLE
phase1 배포 작업 (~9/30)

### ISSUE THREAD

**Issue by phk1128** [FashionForecast/FashionForecast-server#94]
### 📄 Describe

1차적으로 비회원 기능만 배포할려고 합니다.

### ✅ Tasks

- [ ] deploy 서브모듈 작성
- [x] deploy 도커스크립트 작성
- [ ] deploy CI/CD 스크립트 작성
- [x] aws 및 nginx 설정
